POST http://localhost:3001/api/blogs
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjVmNzc3MTM5OTY2NDAwMThiMGVlZDBlYyIsImlhdCI6MTYwMTczNjEzMn0.4xs1r0hADxxVbtNpGVXUhQVBZlbXp9m2y1Z85D4Bgyc

{
  "title": "Blog2",
  "author": "Test author2",
  "url": "Test url2",
  "likes": 1
}